### ISSUE TITLE
我是新手，帮我解答下，谢谢大佬们

### ISSUE THREAD

**Issue by amanzyw** [angular-cn/ng-nice#4]
我怎么找ng，把他引入我的工程

**Comment by why520crazy** [comment]
使用 bower install angularjs 、去 https://angularjs.org/ （需要翻墙）下载相应的版本包、或者使用 http://ngnice.com/ 右侧的相关下载去找，目前最新只有1.2.6版本的

**Comment by amanzyw** [comment]
```html
ok，thank you
```

**Comment by why520crazy** [comment]
最新稳定版下载地址  http://ngnice.qiniudn.com/angular-1.3.15.zip

**Comment by amanzyw** [comment]
哦是不是只是引入一个ng就行了，但是好像报很多错误啊
![qq 20150528101310](https://cloud.githubusercontent.com/assets/12579130/7851432/542856a6-0522-11e5-9982-3dff05e0dd48.png)

**Comment by why520crazy** [comment]
引入 后不写一行ng的代码也会报错吗？

**Comment by why520crazy** [comment]
你去看看 入门知识吧

**Comment by why520crazy** [comment]
https://docs.angularjs.org/tutorial

**Comment by amanzyw** [comment]
引入不报错，写ng-model时也不报错，就是自定义模块时候报错的。可能是语法没用对吧，我再去官网看看文档。

**Comment by why520crazy** [comment]
![image](https://cloud.githubusercontent.com/assets/3959960/7851575/dcf5e348-0524-11e5-985f-be36ca7d67d4.png)

helloAngular 不是一个function
